[package]
name = "mind-builder"
version = "0.1.0"
authors = ["Alexandre Chêne <kooparse@protonmail.com>"]
edition = "2018"

[dependencies]
engine = { path = "engine" }

[workspace]
members = ["engine"]

[[bin]]
name = "game"
path = "game/src/main.rs"

