[package]
name = "editor"
version = "0.1.0"
authors = ["Alexandre Chêne <kooparse@protonmail.com>"]
edition = "2018"

[dependencies]
nalgebra-glm = "0.4.2"
renderer = { path = "../renderer" }
engine = { path = "../engine" }

