[package]
name = "renderer"
version = "0.1.0"
authors = ["Alexandre Chêne <kooparse@protonmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gl = "0.13.0"
nalgebra-glm = "0.3"
image = "0.22.1"
gltf = "0.13"
