[package]
name = "renderer"
version = "0.1.0"
authors = ["Alexandre Chêne <kooparse@protonmail.com>"]
edition = "2018"

[dependencies]
gl = "0.13.0"
nalgebra-glm = "0.4.2"
image = "0.22.1"
gltf = "0.13"
